#!/usr/bin/node
const { argv } = require('node:process');
argv.forEach((val, index) => {
	
		if ( process.argv.lenght < 3){
			console.log('No argument');
			process.exit(1);
		}
	else{
		console.log(`${val} `);}
});
